### ISSUE TITLE
"same file descriptor" warning on amdgpu

### ISSUE THREAD

**Issue by NorwegianRockCat** [freebsd/drm-kmod#21] opened 2020-08-23 08:53 UTC
Not sure if this is a bug or enhancement, but we do get this warning from time-to-time with the amdgpu (for example when running `X` or `vdpauinfo` with a NAVI10 card. 
```
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
```
Apparently this is handled via the kcmp syscall on Linux, at least according to this [commit from Gentoo](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=ee5e5804a9a10db5fd95022efe5e9217b56dd6d1).

Probably kcmp is not implemented yet on FreeBSD? At this point, it's hard to know "bad things" are actually happening (I don't understand how the DRM fds work, but I guess there are two here since it seems strange to see the message otherwise). So, it might point to problems in the future, and it therefore might be something worth fixing if its easy enough to implement.

**Comment by myfreeweb** [comment] 2020-09-04 16:41
I have encountered this when debugging VAAPI, but it didn't seem to cause any problems, and messing with Mesa's `os_same_file_description` didn't help.

It would definitely be nice to have a `kcmp` style syscall, at least without the cross-process functionality..

**Comment by jbeich** [comment] 2020-09-28 08:56
Try https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/6881. On Intel with mesa-devel starting `sway` and `mpv --gpu-context=drm` showed:
```
WARNING: Kernel has no file descriptor comparison support: No error: 0
```

**Comment by grahamperrin** [comment] 2022-04-18 18:34
Cross-reference: [xorg not starting with amdgpu | The FreeBSD Forums](https://forums.freebsd.org/threads/xorg-not-starting-with-amdgpu.76131/) (2020-11-07)

**Comment by rahul-singh-sandhu** [comment] 2023-03-11 22:37
Now this is where things get weirder - I can open xorg de's/wm's/sessions, but I cant do anything wayland. my gpu is a radeon pro wx7100, and I end up with this:

rahulsandhu@bsd ~ # sway           
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
00:00:00.081 [wlr] [types/wlr_drm_lease_v1.c:716] No DRM backend supplied, failed to create wlr_drm_lease_v1_manager
00:00:00.081 [sway/server.c:231] Unable to open wayland socket

**Comment by valpackett** [comment] 2023-03-13 04:43
@rahul-singh-sandhu the warning from this thread is irrelevant. The other messages [should also be harmless](https://www.reddit.com/r/swaywm/comments/108bb3x/harmless_error_message_on_amd_gpu/). Except `Unable to open wayland socket`, which must be related to your `XDG_RUNTIME_DIR` or something.

**Comment by evadot** [comment] 2023-03-13 07:07
> @rahul-singh-sandhu the warning from this thread is irrelevant. The other messages [should also be harmless](https://www.reddit.com/r/swaywm/comments/108bb3x/harmless_error_message_on_amd_gpu/). Except `Unable to open wayland socket`, which must be related to your `XDG_RUNTIME_DIR` or something.

IIRC when you don't have XDG_RUNTIME_DIR it's written, I think that this error is when you don't have seatd running.

**Comment by ctipper** [comment] 2023-05-14 09:33
Sorry for the interjection but I just stumbled into this bug on my server, running FreeBSD 13.2 just upgraded last week. X won't start and I've gone back to scfb it's amdgpu. Is the issue mesa, drm or X, I'm confused. This was a stable installation for 18 months and it just started happening.

**Comment by thedaemon** [comment] 2023-09-17 23:00
I have a Navy Flounder card, 6750XT, and also have this warning. I am also having hard system locks, where the only thing I can do is hard reset with the power button. I have yet to find a log showing where the issue is. If you could point me in the right direction I could do better research into my own system. I will post back or create a new report if I find something useful.

**Comment by valpackett** [comment] 2023-09-17 23:58
Once again everyone, PSA: the warning is unrelated to any actual issues.

@thedaemon check if it's an actual kernel freeze or just a display output freeze by having an SSH connection open into the box, if it's an actual kernel hang that's kinda the hardest kind of issue to debug..

**Comment by evadot** [comment] 2024-04-17 08:33
Closing as FreeBSD 14/15 have kcmp now.

**Closed by evadot** 2024-04-17 08:33 UTC
Labels: amdgpu
